org.gradle.jvmargs=-Xmx4G
minecraft_version=1.21.10
mod_version=0.0.7
mod_id=reterraforged
maven_group=raccoonman.reterraforged
fabric_loader_version=0.18.0
fabric_api_version=0.138.0
terrablender_version=21.10.0.0
lithostitched_version=1.5.1
neoforge_version=21.10.49-beta
oh_the_trees_youll_grow_version=8.0.2